; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
test_ignore = test_logic

board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.disable_embedded_libs = yes
board_build.ldscript = $PROJECT_DIR/STM32F103xx_FLASH.ld

lib_archive = no

build_flags =
    -I include
    -I lib/FreeRTOS/include
    -I lib/FreeRTOS/portable/GCC/ARM_CM3
    -fno-exceptions
    -fno-rtti

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
    +<alarm_logic.cpp>
    +<display_navigation.cpp>
    +<sensor_values.cpp>
    +<system_state.cpp>
build_flags =
    -I include